apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: fabricioveronez/web-color:blue
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
    # Informar na label do Service o nome da aplicação que ele expõe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # A porta exposta pelo meun Deployment
  type: LoadBalancer